[package]
name = "native_rust_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
jni = "0.21.1"
arrow = "52.0.0"
parquet =  { version ="52.0.0", features = ["arrow"] }
serde_json = "1.0"
base64 = "0.22.0"
libc = "0.2.155"

[lib]
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "native_rust_lib"
path = "src/main.rs"
