[package]
name = "tsdb_timon"
version = "1.0.10"
edition = "2021"
authors = ["Ahmed Boutaraa <ahmed@mongrov.com>"]
description = "Efficient local storage and Amazon S3-compatible data synchronization for time-series data, leveraging Parquet for storage and DataFusion for querying, all wrapped in a simple and intuitive API."
license = "Apache-2.0"
repository = "https://github.com/mongrov/timon"
keywords = ["parquet", "datafusion", "apache-arrow", "tsdb", "S3-storage-sync"]
categories = ["embedded", "database", "filesystem"]

[dependencies]
jni = "0.21.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.137"
base64 = "0.22.1"
libc = "0.2.155"
datafusion = "44.0"
tokio = { version = "1", features = ["full"] }
regex = "1.10.6"
object_store = { version = "0.11.2", features = ["aws"] }
url = { version = "2.5.2" }
chrono = "0.4.38"
hex = "0.4.3"
clap = { version = "4.5.27", features = ["derive"], optional = true }
actix-web = { version = "4.9.0", optional = true }
actix-web-httpauth = { version = "0.8.2", optional = true }
jsonwebtoken = { version = "9.3.0", optional = true }
log = { version = "0.4.25", optional = true }
env_logger = { version = "0.11.6", optional =  true }

[features]
dev_cli = ["clap"]
cloud_server = ["actix-web", "actix-web-httpauth", "jsonwebtoken", "log", "env_logger"]

[lib]
name = "tsdb_timon"
crate-type = ["staticlib", "cdylib", "lib"]

[profile.release]
debug = 0
lto = "fat"
opt-level = 'z'
split-debuginfo = "off"
codegen-units = 1
strip = "symbols"
panic = "abort"
